-- Asset Management Assistant — schema
--
-- Provenance is tracked in-band via the `source` columns:
--   'xlsx'      = value came from Sample_Asset_Master.xlsx unchanged
--   'synthetic' = value generated by seed.py to satisfy a functional
--                 requirement the source file cannot answer (manager
--                 hierarchy, asset availability). See README "Data provenance".

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS employees (
    employee_id  TEXT PRIMARY KEY,
    full_name    TEXT NOT NULL UNIQUE,
    email        TEXT NOT NULL,
    department   TEXT NOT NULL,
    location     TEXT NOT NULL,
    manager_id   TEXT REFERENCES employees (employee_id),
    source       TEXT NOT NULL CHECK (source IN ('xlsx', 'synthetic'))
);

CREATE TABLE IF NOT EXISTS assets (
    asset_code    TEXT PRIMARY KEY,
    asset_name    TEXT NOT NULL,
    category      TEXT NOT NULL,
    employee_id   TEXT REFERENCES employees (employee_id),
    location      TEXT NOT NULL,
    purchase_date TEXT NOT NULL,                    -- ISO-8601 date
    status        TEXT NOT NULL CHECK (status IN ('Assigned', 'Available', 'In Repair', 'Retired')),
    condition     TEXT NOT NULL CHECK (condition IN ('New', 'Good', 'Fair', 'Poor')),
    source        TEXT NOT NULL CHECK (source IN ('xlsx', 'synthetic')),
    updated_at    TEXT NOT NULL,                    -- ISO-8601 timestamp, drives optimistic concurrency

    -- An asset is held by exactly one person or by nobody. Enforcing the
    -- invariant here means no tool can write an inconsistent row.
    CHECK (
        (status = 'Assigned' AND employee_id IS NOT NULL)
        OR (status <> 'Assigned' AND employee_id IS NULL)
    )
);

-- Append-only audit log. Every mutation performed by the agent lands here.
CREATE TABLE IF NOT EXISTS asset_transfers (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    asset_code       TEXT NOT NULL REFERENCES assets (asset_code),
    action           TEXT NOT NULL CHECK (action IN ('create', 'transfer', 'unassign')),
    from_employee_id TEXT REFERENCES employees (employee_id),
    to_employee_id   TEXT REFERENCES employees (employee_id),
    reason           TEXT,
    actor            TEXT NOT NULL,                 -- who asked for it
    session_id       TEXT,
    idempotency_key  TEXT UNIQUE,                   -- replay protection
    transferred_at   TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_assets_search   ON assets (category, location, status);
CREATE INDEX IF NOT EXISTS idx_assets_employee ON assets (employee_id);
CREATE INDEX IF NOT EXISTS idx_assets_name     ON assets (asset_name);
CREATE INDEX IF NOT EXISTS idx_emp_manager     ON employees (manager_id);
CREATE INDEX IF NOT EXISTS idx_transfers_asset ON asset_transfers (asset_code);
